version: '3'

services:
  app:
    container_name: shipping-ms
    image: orders-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge